<?php
foreach($xmlData['Urunler']['Urun'] as $k=>$v){
	array_push($bisiatData,array(
		'code'                      =>$v['UrunSecenek']['Secenek']['VaryasyonID'],
		'ws_code'                   =>$v['UrunSecenek']['Secenek']['VaryasyonID'],
		'barcode'                   =>$v['UrunSecenek']['Secenek']['Barkod'],
		'supplier_code'             =>$v['UrunSecenek']['Secenek']['Barkod'],
		'name'                      =>$v['UrunAdi'],
		'product_link'              =>$v['UrunUrl'],
		'cat1name'                  =>'',
		'cat1code'                  =>'',
		'cat2name'                  =>'',
		'cat2code'                  =>'',
		'cat3name'                  =>$v['KategoriTree'],
		'cat3code'                  =>'',
		'category_path'             =>$v['KategoriTree'],
		'stock'                     =>$v['UrunSecenek']['Secenek']['StokAdedi'],
		'unit'                      =>$v['SatisBirimi'],
		'price_list'                =>'',
		'price_list_campaign'       =>'',
		'price_special_vat_included'=>$v['UrunSecenek']['Secenek']['SatisFiyati'],
		'price_special_rate'        =>'',
		'price_special'             =>'',
		'min_order_quantity'        =>'',
		'price_credit_card'         =>'',
		'currency'                  =>$v['UrunSecenek']['Secenek']['ParaBirimi'],
		'vat'                       =>$v['UrunSecenek']['Secenek']['KdvOrani'],
		'brand'                     =>$v['Marka'],
		'model'                     =>$v['UrunSecenek']['Secenek']['VaryasyonID'],
		'desi'                      =>$v['UrunSecenek']['Secenek']['Desi'],
		'width'                     =>'',
		'height'                    =>'',
		'deep'                      =>'',
		'weight'                    =>'',
		'detail'                    =>$v['Aciklama'],
		'seo_title'                 =>$v['SeoSayfaBaslik'],
		'seo_description'           =>$v['SeoAciklama'],
		'seo_keywords'              =>$v['SeoAnahtarKelime'],
		'images'                    =>json_encode($v['Resimler']['Resim'],true),
		'subproducts'               =>'',
		'xml_id'                    =>$selectedXml['data'][0]['id'],
		'cariID'                    =>$mercId,
		'storeID'                   =>$storeId,
		'catId'                     =>(isset($v['KategoriTree'])?findCat($v['KategoriTree']):0),
		'deliveryTemplate'          =>$templateId,
		'status'                    =>1,
		'brand_id'                  =>findBrand($v['Marka']),
		'attributes'                =>'',
		'color'                     =>$v['OzelAlan2'],
		'size'                      =>'',
	));
}
?>