<?php
foreach($xmlData['product'] as $k=>$v){
	array_push($bisiatData,array(
		'code'                      =>$v['sku'],
		'ws_code'                   =>$v['sku'],
		'barcode'                   =>$v['barcode'],
		'supplier_code'             =>$v['barcode'],
		'name'                      =>$v['name'],
		'product_link'              =>'',
		'cat1name'                  =>'',
		'cat1code'                  =>'',
		'cat2name'                  =>'',
		'cat2code'                  =>'',
		'cat3name'                  =>$v['productCategory'],
		'cat3code'                  =>'',
		'category_path'             =>$v['productCategory'],
		'stock'                     =>$v['quantity'],
		'unit'                      =>'',
		'price_list'                =>'',
		'price_list_campaign'       =>'',
		'price_special_vat_included'=>$v['price'],
		'price_special_rate'        =>'',
		'price_special'             =>'',
		'min_order_quantity'        =>'',
		'price_credit_card'         =>'',
		'currency'                  =>'TL',
		'vat'                       =>8,
		'brand'                     =>$v['productBrand'],
		'model'                     =>'',
		'desi'                      =>'',
		'width'                     =>'',
		'height'                    =>'',
		'deep'                      =>'',
		'weight'                    =>'',
		'detail'                    =>$v['description'],
		'seo_title'                 =>'',
		'seo_description'           =>'',
		'seo_keywords'              =>'',
		'images'                    =>json_encode(array($v['imgUrl']),true),
		'subproducts'               =>'',
		'xml_id'                    =>$selectedXml['data'][0]['id'],
		'cariID'                    =>$mercId,
		'storeID'                   =>$storeId,
		'catId'                     =>(isset($v['productCategory'])?findCat($v['productCategory']):0),
		'deliveryTemplate'          =>$templateId,
		'status'                    =>1,
		'brand_id'                  =>findBrand($v['productBrand']),
		'attributes'                =>'',
		'color'                     =>'',
		'size'                      =>'',
	));
}
?>